CREATE TABLE IF NOT EXISTS subjects (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  color TEXT NOT NULL DEFAULT '#b87040',
  created_at INTEGER NOT NULL
);

ALTER TABLE notes ADD COLUMN subject_id TEXT DEFAULT NULL;
